<BaseMDNavigationItem>

    MDNavigationItemIcon:
        icon: root.icon

    MDNavigationItemLabel:
        text: root.text


<BaseScreen>

<ProjectListItem>

    MDListItemLeadingIcon:
        icon: "account"

    MDListItemHeadlineText:
        text: root.name


<HomeScreen@BaseScreen>

    app: app
    projects: app.projects.projects

    ScrollView:
        pos_hint: {'top': 0.9}
        MDList:
            id: list_of_projects

    MDFabButton:
        icon: "pencil-outline"
        style: "standard"
        pos_hint: {"center_x": .9, "center_y": .2}
        on_release: app.create_project()


<SettingsScreen@BaseScreen>

    MDLabel:
        text: "Settings"
        halign: "center"
        pos_hint: {"center_x": .5, "center_y": .8}

    # Token editor
    MDTextField:
        pos_hint: {"center_x": .5, "center_y": .6}
        on_text: app.on_token_change(*args)
        text: app.settings.openapi_token

        MDTextFieldLeadingIcon:
            icon: "account"

        MDTextFieldHintText:
            text: "sk-....."

        MDTextFieldHelperText:
            text: "Enter your OpenAI token here."
            mode: "persistent"


<ProjectScreen@BaseScreen>

    MDLabel:
        text: "Project Settings"
        halign: "center"
        pos_hint: {"center_x": .5, "center_y": .9}

    # System Prompt
    MDTextField:
        pos_hint: {"center_x": .5, "center_y": .6}
        text: app.project and app.project.system_prompt or ""
        on_text: app.project.system_prompt = args[1]
        multiline: True
        mode: "filled"

        MDTextFieldLeadingIcon:
            icon: "application-array-outline"

        MDTextFieldHintText:
            text: "Ти творчий помічник, який допомагає генерувати ..."

        MDTextFieldHelperText:
            text: "Enter System Prompt here"
            mode: "persistent"


MDScreen:
    md_bg_color: self.theme_cls.backgroundColor

    MDScreenManager:
        id: screen_manager

        HomeScreen:
            name: "Home"

        BaseScreen:
            name: "Create Post"

        BaseScreen:
            name: "Saved Posts"

        SettingsScreen:
            name: "Settings"

        ProjectScreen:
            name: "Project Settings"

    MDTopAppBar:
        type: "small"
        size_hint_x: 1.0
        pos_hint: {"top": 1.0}
        id: top_app_bar

        MDTopAppBarLeadingButtonContainer:

            MDActionTopAppBarButton:
                icon: "menu"

        MDTopAppBarTitle:
            text: app.project and app.project.name or "No project selected"

        AnchorLayout:
            anchor_x: "right"
            anchor_y: "top"
            pos_hint: {"right": 1.0}
            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "application-array-outline"
                    on_release: app.show_project_settings()



    # A bottom navigation bar with icons for Home, Create Post, Saved Posts, and Settings.

    MDNavigationBar:
        on_switch_tabs: app.on_switch_tabs(*args)

        BaseMDNavigationItem
            icon: "home"
            text: "Home"
            active: True

        BaseMDNavigationItem
            icon: "note-edit"
            text: "Create Post"

        BaseMDNavigationItem
            icon: "content-save"
            text: "Saved Posts"

        BaseMDNavigationItem
            icon: "application-settings"
            text: "Settings"
